### ISSUE TITLE
Feature request: limit the queue size

### ISSUE THREAD

**Issue by dandv** [lpinca/valvelet#2]
See https://github.com/xavi-/node-simple-rate-limiter/issues/5

**Comment by lpinca** [comment]
What would you do when the queue is at capacity? Reject the promise?

**Comment by dandv** [comment]
Yes. @markstos, what do you think?

**Comment by markstos** [comment]
Rejecting a promise-- equivalent of throwing an exception-- would be fine in this case. The queue limit is meant to be a limit that allows the application and developer some control over the failure when the limit is passed, and to prevent a more traumatic failure when memory is fully exhausted, so the system is swamped and there's no control over how it fails. 

Like memory filling up completely, the queue limit is ideally set a level that should rarely be reached. If it's reached, there's a serious problem, so starting to raise alarms by rejecting promises becomes a reasonable behavior.

**Comment by lpinca** [comment]
Yes it makes sense, my only concern is when using `Promise.all()`. If valvelet returns a rejected promise, because the queue is full, the promise returned by `Promise.all()` will be rejected but I guess it is how it is supposed to work.

Mind to send a pr for this?

**Comment by lpinca** [comment]
Anyway an hard limit is already set.
An array, per spec, can contain at max 2^32 -1 elements. If you try to push a new element an error is thrown:

``` js
> const arr = new Array(4294967295)
undefined
> arr.push('foo')
RangeError: Invalid array length
    at repl:1:5
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:224:10)
    at REPLServer.Interface._line (readline.js:566:8)
    at REPLServer.Interface._ttyWrite (readline.js:843:14)
```

When this [happens](https://github.com/lpinca/valvelet/blob/f7a770e3203359d643e9820c748e0ed872add855/index.js#L32) valvelet returns a rejected promise.

**Comment by markstos** [comment]
Given a common array element size, how much memory would be consumed when
the queue has reached a size of 2^32 -1 elements. Is that a reasonable
limit?

On Thu, Jun 30, 2016 at 3:23 PM, Luigi Pinca notifications@github.com
wrote:

> Anyway an hard limit is already set.
> An array, per spec, can contain at max 2^32 -1 elements. If you try to
> push a new element an error is thrown:
> 
> > const arr = new Array(4294967295)undefined> arr.push('foo')
> > RangeError: Invalid array length
> >     at repl:1:5
> >     at REPLServer.defaultEval (repl.js:272:27)
> >     at bound (domain.js:280:14)
> >     at REPLServer.runBound [as eval](domain.js:293:12)
> >     at REPLServer.<anonymous> (repl.js:441:10)
> >     at emitOne (events.js:101:20)
> >     at REPLServer.emit (events.js:188:7)
> >     at REPLServer.Interface._onLine (readline.js:224:10)
> >     at REPLServer.Interface._line (readline.js:566:8)
> >     at REPLServer.Interface._ttyWrite (readline.js:843:14)
> 
> When this happens
> https://github.com/lpinca/valvelet/blob/f7a770e3203359d643e9820c748e0ed872add855/index.js#L32
> valvelet returns a rejected promise.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/lpinca/valvelet/issues/2#issuecomment-229762307, or mute
> the thread
> https://github.com/notifications/unsubscribe/AABk5X4yWaB4pk4YA4sw-doHFJLX3Gghks5qRBe2gaJpZM4JBztr
> .

## 

```
Mark Stosberg
Senior Systems Engineer
RideAmigos
```

**Comment by lpinca** [comment]
That's a good question, it depends on the [arguments](https://github.com/lpinca/valvelet/blob/f7a770e3203359d643e9820c748e0ed872add855/index.js#L29) that get passed to the function as they are kept in the queue.

**Comment by markstos** [comment]
Another way to look at it is that there is already a precedent for rejecting a promise with the queue limit is hit. The question here is whether the implicit default of 2^32 -1 should be lowered. 

Some possible objects that would go in the array can be tested for their memory size with [sizeof](http://code.stephenmorley.org/javascript/finding-the-memory-usage-of-objects/) and then multiplied by the array length to estimate the total memory size of the array. It's possible that before an physical memory would be hit, Node.js or the OS might impose another memory on the maximum size for a single process.

**Comment by lpinca** [comment]
> It's possible that before an physical memory would be hit, Node.js or the OS might impose another memory on the maximum size for a single process.

Yes, If I'm not mistaken each node process by default has a ~1.5 GB limit.

> The question here is whether the implicit default of 2^32 -1 should be lowered.

I agree. It probably makes sense to add an option to customize this. It's also easy to do, so why not.

**Comment by dandv** [comment]
The actual memory limit for [embedded systems](http://embeddednodejs.com/chapters.html) may be far lower than 2**32. Thanks for implementing a customizable limit.
